#!/bin/sh

cd `dirname $0`

. ./lib.sh

echo "--- begin of ubuntuInit"
sudo echo

for i in zsh default-editor git github sshd vim; do
	confirm "!!!!!! deploy $i ?" && $i/deploy
	sudo echo
done

echo "--- complete"
