#!/bin/sh

echo ------ cd `dirname $0`
cd `dirname $0`

echo ------ sudo echo begin setting zsh
sudo echo begin setting zsh

echo ------ sudo apt-get install zsh -y
sudo apt-get install zsh -y

echo ------ cp zshrc ~/.zshrc
cp zshrc ~/.zshrc

echo ------ mkdir -p ~/.zsh
mkdir -p ~/.zsh

echo ------ cp -r sourceFiles/* ~/.zsh
cp -r sourceFiles/* ~/.zsh

echo ------ chsh -s /bin/zsh
chsh -s /bin/zsh

