#!/bin/sh

cd `dirname $0`
. ../lib.sh

echo !!! begin setting zsh
echoAndExec sudo apt-get install zsh -y
echoAndExec cp zshrc ~/.zshrc
echoAndExec mkdir -p ~/.zsh
echoAndExec cp -r sourceFiles/* ~/.zsh
echoAndExec sudo chsh -s /bin/zsh `whoami`
